name = "TimeVaryingParameters"
uuid = "c3441385-f229-4866-8817-bbca1834e4b8"
version = "0.0.1"
authors = ["arnaud-ma <arnaudma.code@gmail.com> and contributors"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinkFunctions = "fa965eab-f9a2-49de-8293-bc60088b3cbc"
OptimizationBase = "bca83a33-5cc9-4baa-983d-23429ab6bcbb"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[weakdeps]
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"

[extensions]
OptimizationOptimJLExt = "OptimizationOptimJL"


[compat]
ADTypes = "1.23.0"
ArgCheck = "2.5.0"
ComponentArrays = "0.15.44"
Dates = "1.11.0"
LinearAlgebra = "1.12.0"
LinkFunctions = "0.1.0"
OptimizationBase = "5.3.0"
OptimizationOptimJL = "0.4"
SciMLBase = "3.48.0"
StatsAPI = "1.8.0"
julia = "1.12.6"
